# Generated by Django 3.0.7 on 2020-06-07 05:12

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkerboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_turn', models.CharField(max_length=1)),
                ('board', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1), size=None), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='SinglePlayerGame',
            fields=[
                ('board', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='api.Checkerboard')),
                ('user_color', models.CharField(max_length=1)),
                ('name', models.CharField(max_length=200)),
                ('game_status', models.CharField(choices=[('unfinished', 'Unfinished'), ('user_won', 'You Won'), ('user_lost', 'You Lost'), ('draw', 'Draw')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='single_player_games', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
