# Generated by Django 3.0.7 on 2020-06-10 20:21

from django.db import migrations, models
from django.utils.timezone import now


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='singleplayergame',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='singleplayergame',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
