# Generated by Django 3.0.7 on 2020-06-12 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200612_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singleplayergame',
            name='game',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Game'),
        ),
    ]
