# Generated by Django 3.0.7 on 2020-06-12 04:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200612_0355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singleplayergame',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='singleplayergame',
            name='name',
        ),
        migrations.RemoveField(
            model_name='singleplayergame',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='game',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
